name: check php releases

on:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run php version update script
      run: cd $GITHUB_WORKSPACE && ./update.sh
