name: check php releases

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '3 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --depth=1 origin '+refs/tags/*:refs/tags/*'
    - name: Run php version update script
      run: cd $GITHUB_WORKSPACE && ./update.sh
